"""empty message

Revision ID: 1645356f862a
Revises: aaceebca7457
Create Date: 2019-06-04 17:21:25.754040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1645356f862a'
down_revision = 'aaceebca7457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userdata', 'enddate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdata', sa.Column('enddate', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
