"""empty message

Revision ID: 1e8fffd4b780
Revises: 60905dae8426
Create Date: 2019-05-24 19:39:55.455365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e8fffd4b780'
down_revision = '60905dae8426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mooddata', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mooddata', 'email')
    # ### end Alembic commands ###
