"""empty message

Revision ID: 44ce800bf270
Revises: 1e8fffd4b780
Create Date: 2019-05-26 21:03:11.232941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ce800bf270'
down_revision = '1e8fffd4b780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mooddata', sa.Column('uniqueidentifier', sa.String(), nullable=True))
    op.drop_column('mooddata', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mooddata', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('mooddata', 'uniqueidentifier')
    # ### end Alembic commands ###
