"""empty message

Revision ID: 60905dae8426
Revises: 11b98d88a787
Create Date: 2019-05-24 15:42:41.125671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60905dae8426'
down_revision = '11b98d88a787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uniqueidentifier', sa.String(), nullable=True),
    sa.Column('waketime', sa.String(), nullable=True),
    sa.Column('sleeptime', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uniqueidentifier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('waketime', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sleeptime', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'user_pkey')
    )
    op.drop_table('userdata')
    # ### end Alembic commands ###
