"""empty message

Revision ID: 78cc1765d2db
Revises: 7a951920dbb8
Create Date: 2019-05-22 13:32:30.954535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78cc1765d2db'
down_revision = '7a951920dbb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mooddata', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mooddata', 'date')
    # ### end Alembic commands ###
