"""empty message

Revision ID: 7a951920dbb8
Revises: 31c0ae5ac0be
Create Date: 2019-05-20 16:10:26.059223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a951920dbb8'
down_revision = '31c0ae5ac0be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mooddata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mooddata')
    # ### end Alembic commands ###
