"""empty message

Revision ID: dcf6cdd3d12e
Revises: 0ef22cb18927
Create Date: 2019-05-31 17:12:32.823850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf6cdd3d12e'
down_revision = '0ef22cb18927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdata', sa.Column('carriersettings', sa.String(), nullable=True))
    op.add_column('userdata', sa.Column('phonenumber', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userdata', 'phonenumber')
    op.drop_column('userdata', 'carriersettings')
    # ### end Alembic commands ###
